server:
  port: 8080
  servlet:
    context-path: /images

management:
  endpoints:
    web:
      exposure:
        include: check

spring:
  application:
    name: image_service

cloud:
  aws:
    region:
      static: ${REGION}
    credentials:
      accessKey: ${ACCESS_KEY_ID}
      secretKey: ${SECRET_ACCESS_KEY}

dynamoDb:
  tableName: ${TABLE_NAME}

s3:
  bucketName: ${BUCKET_NAME}