#server:
#  port: 8081
#  servlet:
#    context-path: /image

spring:
  application:
    name: image_service

aws:
  accessKeyId: ${ACCESS_KEY_ID}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  region: ${REGION}